package dev.novaforge.engine.core.blocks

import org.json.JSONArray
import org.json.JSONObject

/** NovaBlocks IR: UI -> versioned graph -> deterministic Lua. */
data class BlockGraph(
    val formatVersion: Int = 1,
    val scripts: MutableList<BlockScript> = mutableListOf()
) {
    fun toJson(): String = JSONObject()
        .put("formatVersion", formatVersion)
        .put("scripts", JSONArray().also { a -> scripts.forEach { a.put(it.toJson()) } })
        .toString(2)

    companion object {
        fun fromJson(text: String): BlockGraph {
            val json = JSONObject(text)
            val graph = BlockGraph(json.optInt("formatVersion", 1))
            val scripts = json.optJSONArray("scripts") ?: JSONArray()
            for (i in 0 until scripts.length()) graph.scripts += BlockScript.fromJson(scripts.getJSONObject(i))
            return graph
        }
    }
}

data class BlockScript(
    val event: String,
    val argument: String? = null,
    val body: MutableList<BlockNode> = mutableListOf()
) {
    fun toJson(): JSONObject = JSONObject()
        .put("event", event)
        .put("argument", argument)
        .put("body", JSONArray().also { a -> body.forEach { a.put(it.toJson()) } })

    companion object {
        fun fromJson(json: JSONObject): BlockScript {
            val body = mutableListOf<BlockNode>()
            val array = json.optJSONArray("body") ?: JSONArray()
            for (i in 0 until array.length()) body += BlockNode.fromJson(array.getJSONObject(i))
            return BlockScript(
                json.getString("event"),
                json.optString("argument").takeIf { it.isNotBlank() && it != "null" },
                body
            )
        }
    }
}

data class BlockNode(
    val type: String,
    val fields: MutableMap<String, String> = linkedMapOf(),
    val children: MutableList<BlockNode> = mutableListOf(),
    val elseChildren: MutableList<BlockNode> = mutableListOf()
) {
    fun toJson(): JSONObject = JSONObject()
        .put("type", type)
        .put("fields", JSONObject(fields as Map<*, *>))
        .put("children", JSONArray().also { a -> children.forEach { a.put(it.toJson()) } })
        .put("else", JSONArray().also { a -> elseChildren.forEach { a.put(it.toJson()) } })

    companion object {
        fun fromJson(json: JSONObject): BlockNode {
            val fields = linkedMapOf<String, String>()
            json.optJSONObject("fields")?.let { f -> f.keys().forEach { fields[it] = f.optString(it) } }
            fun decodeArray(name: String): MutableList<BlockNode> = mutableListOf<BlockNode>().also { out ->
                val a = json.optJSONArray(name) ?: JSONArray()
                for (i in 0 until a.length()) out += fromJson(a.getJSONObject(i))
            }
            return BlockNode(json.getString("type"), fields, decodeArray("children"), decodeArray("else"))
        }
    }
}

data class BlockDefinition(val id: String, val category: String, val label: String)

object BlockRegistry {
    val definitions = listOf(
        BlockDefinition("move_x", "Movement", "Alterar X por ()"),
        BlockDefinition("move_y", "Movement", "Alterar Y por ()"),
        BlockDefinition("set_x", "Transform", "Definir X para ()"),
        BlockDefinition("set_y", "Transform", "Definir Y para ()"),
        BlockDefinition("rotate", "Transform", "Rotacionar por ()"),
        BlockDefinition("send_signal", "Signals", "Enviar sinal []"),
        BlockDefinition("set_variable", "Variables", "Definir variável [] para ()"),
        BlockDefinition("change_variable", "Variables", "Alterar variável [] por ()"),
        BlockDefinition("if", "Control", "Se <condição>"),
        BlockDefinition("if_else", "Control", "Se / Senão"),
        BlockDefinition("wait", "Time", "Esperar () segundos"),
        BlockDefinition("print", "Debug", "Imprimir ()"),
        BlockDefinition("destroy_self", "Objects", "Destruir este objeto")
    )

    val categories = listOf(
        "Events", "Movement", "Transform", "Variables", "Math", "Logic", "Control", "Signals",
        "Input", "Touch", "Objects", "Scenes", "Camera", "UI", "Audio", "Time", "Strings", "Lists",
        "Physics", "Debug", "Functions"
    )
}

object NovaBlocksCompiler {
    fun compile(graph: BlockGraph): String = buildString {
        appendLine("-- Generated by NovaBlocks. Do not edit this generated buffer directly.")
        appendLine("local __nf_vars = {}")
        graph.scripts.forEachIndexed { index, script ->
            when (script.event) {
                "ready" -> function("ready", script.body)
                "update" -> function("update", script.body, "delta")
                "fixed_update" -> function("fixedUpdate", script.body, "delta")
                "touch" -> function("onTouch", script.body, "event")
                "signal" -> {
                    val signal = luaString(script.argument ?: "signal")
                    appendLine("NovaForge.onSignal($signal, function(signalValue)")
                    emitNodes(script.body, "    ")
                    appendLine("end)")
                }
                "pressed" -> function("onPressed_${index}", script.body)
            }
        }
    }

    private fun StringBuilder.function(name: String, body: List<BlockNode>, args: String = "") {
        appendLine("function $name($args)")
        emitNodes(body, "    ")
        appendLine("end")
    }

    private fun StringBuilder.emitNodes(nodes: List<BlockNode>, indent: String) {
        nodes.forEach { node ->
            when (node.type) {
                "move_x" -> appendLine("${indent}self.x = self.x + ${expr(node.fields["value"] ?: "0")}")
                "move_y" -> appendLine("${indent}self.y = self.y + ${expr(node.fields["value"] ?: "0")}")
                "set_x" -> appendLine("${indent}self.x = ${expr(node.fields["value"] ?: "0")}")
                "set_y" -> appendLine("${indent}self.y = ${expr(node.fields["value"] ?: "0")}")
                "rotate" -> appendLine("${indent}self.rotation = self.rotation + ${expr(node.fields["value"] ?: "0")}")
                "send_signal" -> appendLine("${indent}NovaForge.emitSignal(${luaString(node.fields["name"] ?: "signal")}, ${expr(node.fields["value"] ?: "nil")})")
                "set_variable" -> appendLine("${indent}__nf_vars[${luaString(node.fields["name"] ?: "value")}] = ${expr(node.fields["value"] ?: "0")}")
                "change_variable" -> {
                    val key = luaString(node.fields["name"] ?: "value")
                    appendLine("${indent}__nf_vars[$key] = (__nf_vars[$key] or 0) + ${expr(node.fields["value"] ?: "0")}")
                }
                "if", "if_else" -> {
                    appendLine("${indent}if ${expr(node.fields["condition"] ?: "false")} then")
                    emitNodes(node.children, "$indent    ")
                    if (node.elseChildren.isNotEmpty()) {
                        appendLine("${indent}else")
                        emitNodes(node.elseChildren, "$indent    ")
                    }
                    appendLine("${indent}end")
                }
                "print" -> appendLine("${indent}NovaForge.print(${expr(node.fields["value"] ?: "\"\"")})")
                "destroy_self" -> appendLine("${indent}self:destroy()")
                "wait" -> appendLine("${indent}-- wait(${expr(node.fields["seconds"] ?: "0")}) requires coroutine runtime support")
                else -> appendLine("${indent}-- Unsupported block '${node.type}' retained in IR")
            }
        }
    }

    private fun expr(raw: String): String {
        val value = raw.trim().ifEmpty { "0" }
        require(value.length <= 240) { "Expression too long" }
        require(value.matches(Regex("[A-Za-z0-9_ .,+\\-*/%()<>!=\\[\\]'\"#:]*"))) { "Unsafe NovaBlocks expression" }
        return value.replace("delta time", "delta", ignoreCase = true)
    }

    private fun luaString(value: String): String = "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
}
